version: '3'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: starflow
      TZ: Asia/Shanghai
    ports:
      - 3308:3306
    volumes:
      - ./mysql:/var/lib/mysql

  
